#!/bin/bash -x

if [ `command -v curl` ]; then
  curl -sL https://releases.rancher.com/install-docker/${docker_version}.sh | sh
elif [ `command -v wget` ]; then
  wget -qO- https://releases.rancher.com/install-docker/${docker_version}.sh | sh
fi

mkdir /sftp

docker pull atmoz/sftp
sleep 2

docker run \
    -v /sftp:/home \
    --restart=unless-stopped \
    -p ${sftp_port}:22 -d atmoz/sftp \
    '${sftp_user}:${sftp_password}:::upload'
